# This is the implicit global project's config file, which is only used when
# 'stack' is run outside of a real project.  Settings here do _not_ act as
# defaults for all projects.  To change stack's default settings, edit
# '/Users/icylace/.stack/config.yaml' instead.
#
# For more information about stack's configuration, see
# http://docs.haskellstack.org/en/stable/yaml_configuration/
#
packages: []
resolver: nightly-2018-10-31

extra-deps:
  # `stack hoogle` dependency.
  - storable-tuple-0.0.3.3@sha256:1096df92bed234a5dbd3d5b9632131c1b839787b20031c3e179e44493f5939d5
