# ABSEApp
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man1/ABSEApp.1
complete -c ABSEApp -s a --description 'Description of -a flag.'
complete -c ABSEApp -s b --description 'Description of -b flag \\" Ends the list Pp .'

