# ac
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man8/ac.8
complete -c ac -s d --description 'Display the connect times in 24 hour chunks.'
complete -c ac -s p --description 'Display individual user totals.'
complete -c ac -s w --description 'Read raw connect time data from file, instead of the system log.  users .'

