# addftinfo
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man1/addftinfo.1
complete -c addftinfo -s v --description 'prints the version number.'

