# afhash
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man1/afhash.1
complete -c afhash -s h --description 'print help text.'
complete -c afhash -s w --description 'write hash code to audio file.'
complete -c afhash -s x --description 'print hash code from audio file (if present).'
complete -c afhash -s c --description 'compare hash codes from two audio files El.'

