# agentxtrap
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man1/agentxtrap.1
complete -c agentxtrap -s c --description 'if the  -c option is present then the notification is sent in the nondefault …'
complete -c agentxtrap -s U --description 'if the  -U option is present then that value, parsed as centiseconds, is take…'
complete -c agentxtrap -s x --description 'if the  -x option is present then contact the AgentX master at ADDRESS and no…'
complete -c agentxtrap -s d -s D -s m -s M --description 'options are supported.'

