# apfs
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man8/apfs.util.8
complete -c apfs -s p --description 'Probe the device to determine whether it contains an apfs volume.'
complete -c apfs -s k --description 'Return the UUID of the apfs volume on device.'
complete -c apfs -s s --description 'Set UUIDs for the container and the volume(s) on the device to new random val…'

