# appleeventsd
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man8/appleeventsd.8
complete -c appleeventsd -l server --description '.'
complete -c appleeventsd -l noStartupNotification --description '.'

