# asctl
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man1/asctl.1
complete -c asctl -s p --description 'By default, asctl displays paths relative to the user\'s home directory.'
complete -c asctl -s l --description 'Write internal logging information to a temporary file.'

