# catimg
# Autogenerated from man page /usr/local/share/man/man1/catimg.1
complete -c catimg -s h --description 'Prints a help message.'
complete -c catimg -s w --description 'Specify the width of the displayed image, by default catimg will use the term…'
complete -c catimg -s l --description 'Specify the amount of loops that catimg should repeat a GIF.'
complete -c catimg -s r --description 'Possible values 1 or 2.  Force the resolution of the image.'
complete -c catimg -s c --description 'Convert colors to a restricted palette.'

