# cc_fips_test
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man1/cc_fips_test.1
complete -c cc_fips_test -s a --description 'Description of -a flag.'
complete -c cc_fips_test -s b --description 'Description of -b flag \\" Ends the list Pp .'

