# cd9660
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man8/cd9660.util.8
complete -c cd9660 -s m --description 'mount.'
complete -c cd9660 -s p --description 'probe for mounting.'
complete -c cd9660 -s u --description 'unmount El Pp mountflags above are either: -bullet It removable or fixed It r…'

