# cdknowledgetool
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man1/cdknowledgetool.1
complete -c cdknowledgetool -s a --description 'Description of -a flag.'
complete -c cdknowledgetool -s b --description 'Description of -b flag \\" Ends the list Pp .'

