# cksum
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man1/cksum.1
complete -c cksum -s o --description 'Use historic algorithms instead of the (superior) default one.'

