# colldef
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man1/colldef.1
complete -c colldef -s I --description 'Set directory name where charmap files can be found, current directory by def…'
complete -c colldef -s o --description 'Set output file name, LC_COLLATE by default.'

