# comm
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man1/comm.1
complete -c comm -s 1 --description 'Suppress printing of column 1.'
complete -c comm -s 2 --description 'Suppress printing of column 2.'
complete -c comm -s 3 --description 'Suppress printing of column 3.'
complete -c comm -s i --description 'Case insensitive comparison of lines.'

