# compress
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man1/compress.1
complete -c compress -s b --description 'The code size (see below) is limited to bits, which must be in the range 9.'
complete -c compress -s c --description 'Compressed or uncompressed output is written to the standard output.'
complete -c compress -s f --description 'Files are overwritten without prompting for confirmation.'
complete -c compress -s v --description 'Print the percentage reduction of each file.'

