# comsat
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man8/comsat.8
complete -c comsat -s l --description 'The l option turns on syslogd 8 log messages.'

