# corelist5
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man1/corelist5.18.1
complete -c corelist5 -s r --description 'lists all of the perl releases and when they were released .'
complete -c corelist5 -l feature -s f --description 'lists the first version bundle of each named feature given.'

