# cron
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man8/cron.8
complete -c cron -s s --description 'Enable special handling of situations when the GMT offset of the local timezo…'
complete -c cron -s o --description 'Disable the special handling of situations when the GMT offset of the local t…'
complete -c cron -s x --description 'Enable writing of debugging information to standard output.'

