# csgather
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man1/csgather.1
complete -c csgather -s G --description 'Gather all CoreStorage metadata and write into the specified directory.'
complete -c csgather -s o --description 'Specify the output file generated by the -r option.'
complete -c csgather -s r --description 'Find out the CoreStorage logical volume identified by the given mount point, …'

