# cups-lpd
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man8/cups-lpd.8.gz
complete -c cups-lpd -s h --description 'Sets the CUPS server (and port) to use.'
complete -c cups-lpd -s n --description 'Disables reverse address lookups; normally  cups-lpd will try to discover the…'
complete -c cups-lpd -s o --description 'Inserts options for all print queues.'

