# cut
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man1/cut.1
complete -c cut -s b --description 'The list specifies byte positions.'
complete -c cut -s c --description 'The list specifies character positions.'
complete -c cut -s d --description 'Use delim as the field delimiter character instead of the tab character.'
complete -c cut -s f --description 'The list specifies fields, separated in the input by the field delimiter char…'
complete -c cut -s n --description 'Do not split multi-byte characters.'
complete -c cut -s s --description 'Suppress lines with no field delimiter characters.'

