# dbmmanage
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man1/dbmmanage.1
complete -c dbmmanage -s d --description 'crypt encryption (default, except on Win32, Netware).'
complete -c dbmmanage -s m --description 'MD5 encryption (default on Win32, Netware).'
complete -c dbmmanage -s s --description 'SHA1 encryption.'
complete -c dbmmanage -s p --description 'plaintext (not recommended)      . SS "Commands".'

