# dsenableroot
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man8/dsenableroot.8
complete -c dsenableroot -s u --description 'Username of a user that has administrative privileges on this computer.'
complete -c dsenableroot -s p --description 'Password to use in conjunction with the specified username.'
complete -c dsenableroot -s r --description 'Password to be used for the root account.'

