# dspluginhelperd
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man8/dspluginhelperd.8
complete -c dspluginhelperd -s v --description 'Display the release version.'

