# duti
# Autogenerated from man page /usr/local/share/man/man1/duti.1
complete -c duti -s d --description 'display the default handler for  uti and exit.'
complete -c duti -s h --description 'print usage and exit.'
complete -c duti -s l --description 'display all handlers for  uti and exit.'
complete -c duti -s s --description 'set the handler from data provided on the command line.'
complete -c duti -s V --description 'print version number and exit.'
complete -c duti -s v --description 'verbose output.'
complete -c duti -s x --description 'retrieves and prints out information describing the default application for f…'

