# dyld
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man1/dyld.1
complete -c dyld -s L --description 'option to  otool (1).'

