# ed
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man1/ed.1
complete -c ed -s s --description 'Suppress diagnostics.'
complete -c ed -s x --description 'Prompt for an encryption key to be used in subsequent reads and writes (see t…'
complete -c ed -s p --description 'Specify a command prompt.  This may be toggled on and off with the P command.'

