# emlog
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man8/emlog.pl.8
complete -c emlog -s p --description 'Tells emlog to listen on the given local port number, processing the UDP pack…'
complete -c emlog -s l --description 'Tells emlog to process a single line of text then quit.  El Pp .'

