# fingerd
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man8/fingerd.8
complete -c fingerd -s s --description 'Enable secure mode.'
complete -c fingerd -s l --description 'Enable logging.'
complete -c fingerd -s p --description 'Use an alternate program as the local information provider.'

