# fsck
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man8/fsck.8
complete -c fsck -s f --description 'Force fsck to check `clean\' filesystems when preening.'
complete -c fsck -s l --description 'Limit the number of parallel checks to the number specified in the following …'
complete -c fsck -s R --description 'Specify a particular passno number for which fsck is to check.'
complete -c fsck -s p --description '"Preen" mode, described above.'
complete -c fsck -s q --description 'Do a quick check to determine if the filesystem was unmounted cleanly.'
complete -c fsck -s y --description 'Assume a yes response to all questions asked by fsck fsck ; this should be us…'
complete -c fsck -s n --description 'Assume a no response to all questions asked by fsck fsck except for CONTINUE?…'

