# git-tag
# Autogenerated from man page /usr/local/share/man/man1/git-tag.1
complete -c git-tag -s i -l ignore-case --description 'Sorting and filtering tags are case insensitive.'
complete -c git-tag -l no-contains --description 'Only list tags which don\\(cqt contain the specified commit (HEAD if not speci…'
complete -c git-tag -l 'list.' --description '.'
complete -c git-tag -l 'no-merged.' --description '.'
complete -c git-tag -l 'merged.' --description '.'
complete -c git-tag -l no-create-reflog --description 'only overrides an earlier.'

