# git-for-each-ref
# Autogenerated from man page /usr/local/share/man/man1/git-for-each-ref.1
complete -c git-for-each-ref -l no-contains --description 'Only list refs which don\\(cqt contain the specified commit (HEAD if not speci…'
complete -c git-for-each-ref -l ignore-case --description 'Sorting and filtering refs are case insensitive.'
complete -c git-for-each-ref -l 'no-merged.' --description '.'
complete -c git-for-each-ref -l 'merged.' --description '.'
complete -c git-for-each-ref -o '<N>' --description 'path components (e. g.'

