# git-send-pack
# Autogenerated from man page /usr/local/share/man/man1/git-send-pack.1
complete -c git-send-pack -l push-option --description 'Pass the specified string as a push option for consumption by hooks on the se…'

