# git-extras
# Autogenerated from man page /usr/local/share/man/man1/git-extras.1
complete -c git-extras -s v -l version --description 'Show git-extras version number.'
complete -c git-extras -s h -l help --description 'Show this help.  This option can also be used for any of the extras commands.'

