# git-merge-into
# Autogenerated from man page /usr/local/share/man/man1/git-merge-into.1
complete -c git-merge-into -l ff-only --description 'Refuse to merge and exit with a non-zero status unless the current HEAD is al…'

