# git-name-rev
# Autogenerated from man page /usr/local/share/man/man1/git-name-rev.1
complete -c git-name-rev -l exclude --description 'Do not use any ref whose name matches a given shell pattern.'
complete -c git-name-rev -l no-refs --description 'to clear any previous ref patterns given.'
complete -c git-name-rev -l no-exclude --description 'to clear the list of exclude patterns.'

