# git-reauthor
# Autogenerated from man page /usr/local/share/man/man1/git-reauthor.1
complete -c git-reauthor -s a -l all --description '.'
complete -c git-reauthor -s c -l use-config --description '.'
complete -c git-reauthor -s e -l correct-email --description '.'
complete -c git-reauthor -s n -l correct-name --description '.'
complete -c git-reauthor -s o -l old-email --description '.'
complete -c git-reauthor -s t -l type --description '.'

