# git-release
# Autogenerated from man page /usr/local/share/man/man1/git-release.1
complete -c git-release -s r --description 'The "remote" repository that is destination of a push operation: it is passed…'
complete -c git-release -s m --description 'use the custom commit information instead of the default message "Release <ta…'
complete -c git-release -s c --description 'Generates or populates the changelog with all commit message since the last t…'

