# git-standup
# Autogenerated from man page /usr/local/share/man/man1/git-standup.1
complete -c git-standup -s a --description 'The author of commits.  Use "all" means specifying "all authors".'
complete -c git-standup -s m --description 'The depth of recursive directory search.  Defaults to 1.'
complete -c git-standup -s L --description 'Enable the inclusion of symbolic links in recursive directory search.'
complete -c git-standup -s d --description 'The start of commit history.  Defaults to 1, means "1 days ago".'
complete -c git-standup -s D --description 'The date format displayed in commit history.  Defaults to "relative".'
complete -c git-standup -s h --description 'Display help message.'
complete -c git-standup -s g --description 'Display if commit is GPG signed (G) or not (N) in commit message.'
complete -c git-standup -s f --description 'Fetch the latest commits before showing commit history.'

