# git-guilt
# Autogenerated from man page /usr/local/share/man/man1/git-guilt.1
complete -c git-guilt -s h --description 'Output usage information.'
complete -c git-guilt -s e -l email --description 'Display author emails instead of names.'
complete -c git-guilt -s w -l ignore-whitespace --description 'Ignore whitespace only changes when attributing blame.'
complete -c git-guilt -s d -l debug --description 'Output debug information.'

