# git-stash
# Autogenerated from man page /usr/local/share/man/man1/git-stash.1
complete -c git-stash -s m -l message --description 'Save your local modifications to a new stash and roll them back to HEAD (in t…'

