# git-p4
# Autogenerated from man page /usr/local/share/man/man1/git-p4.1
complete -c git-p4 -l shelve --description 'Instead of submitting create a series of shelved changelists.'
complete -c git-p4 -l update-shelve --description 'Update an existing shelved changelist with this commit.  Implies --shelve.'

