# git-rev-parse
# Autogenerated from man page /usr/local/share/man/man1/git-rev-parse.1
complete -c git-rev-parse -l absolute-git-dir --description 'Like --git-dir, but its output is always the canonicalized absolute path.'
complete -c git-rev-parse -l show-superproject-working-tree --description '.'

