# git-rebase
# Autogenerated from man page /usr/local/share/man/man1/git-rebase.1
complete -c git-rebase -l quit --description 'Abort the rebase operation but HEAD is not reset back to the original branch.'
complete -c git-rebase -l signoff --description 'This flag is passed to git am to sign off all the rebased commits (see git-am…'

