# git-shortlog
# Autogenerated from man page /usr/local/share/man/man1/git-shortlog.1
complete -c git-shortlog -s c -l committer --description 'Collect and show committer identities instead of authors.'

