# git-bulk
# Autogenerated from man page /usr/local/share/man/man1/git-bulk.1
complete -c git-bulk -s a --description 'Run a git command on all workspaces and their repositories.'
complete -c git-bulk -s g --description 'Ask the user for confirmation on every execution.'
complete -c git-bulk -s w --description 'Run the git command on the specified workspace.'
complete -c git-bulk -l addworkspace --description 'Register a workspace for bulk operations.'
complete -c git-bulk -l removeworkspace --description 'Remove the workspace with the logical name <ws-name>.'
complete -c git-bulk -l addcurrent --description 'Adds the current directory as workspace to git bulk operations.'

