# git-config
# Autogenerated from man page /usr/local/share/man/man1/git-config.1
complete -c git-config -l inter-hunk-context --description 'command line option.  diff. external.'
complete -c git-config -l 'show-signature.' --description 'log. mailmap.'

