# git-psykorebase
# Autogenerated from man page /usr/local/share/man/man1/git-psykorebase.1
complete -c git-psykorebase -l no-ff --description '.'
complete -c git-psykorebase -l continue --description '.'

