# git-authors
# Autogenerated from man page /usr/local/share/man/man1/git-authors.1
complete -c git-authors -s l -l list --description 'Show authors.'
complete -c git-authors -l no-email --description 'Don\'t show authors\' email.'

