# git-diff
# Autogenerated from man page /usr/local/share/man/man1/git-diff.1
complete -c git-diff -s 1 -l base -s 2 -l ours -s 3 -l theirs --description 'Compare the working tree with the "base" version (stage #1), "our branch" (st…'
complete -c git-diff -s 0 --description 'Omit diff output for unmerged entries and just show "Unmerged".'

