# git-undo
# Autogenerated from man page /usr/local/share/man/man1/git-undo.1
complete -c git-undo -l soft -s s --description 'This is the default, only rolls back the commit but changes remain un-staged.'
complete -c git-undo -l hard -s h --description 'This option wipes your commit(s), so that your changes cannot be recovered.'

