# git-branch
# Autogenerated from man page /usr/local/share/man/man1/git-branch.1
complete -c git-branch -s i -l ignore-case --description 'Sorting and filtering branches are case insensitive.'
complete -c git-branch -l no-contains --description 'Only list branches which don\\(cqt contain the specified commit (HEAD if not s…'
complete -c git-branch -l format --description 'A string that interpolates %(fieldname) from the object pointed at by a ref b…'
complete -c git-branch -l no-create-reflog --description 'only overrides an earlier.'
complete -c git-branch -l 'no-merged.' --description '.'
complete -c git-branch -l 'merged.' --description '<branchname>.'

