# git-merge
# Autogenerated from man page /usr/local/share/man/man1/git-merge.1
complete -c git-merge -l continue --description 'After a git merge stops due to conflicts you can conclude the merge by runnin…'

