# git-read-tree
# Autogenerated from man page /usr/local/share/man/man1/git-read-tree.1
complete -c git-read-tree -l recurse-submodules --description 'Using --recurse-submodules will update the content of all initialized submodu…'

