# git-sed
# Autogenerated from man page /usr/local/share/man/man1/git-sed.1
complete -c git-sed -s c --description 'commit the resulting changes with a standard commit message detailing the exa…'
complete -c git-sed -s f --description 'will use the given regex flags in the sed command (for example "g" replaces m…'

