# git-checkout
# Autogenerated from man page /usr/local/share/man/man1/git-checkout.1
complete -c git-checkout -l recurse-submodules --description 'Using --recurse-submodules will update the content of all initialized submodu…'

