# git-describe
# Autogenerated from man page /usr/local/share/man/man1/git-describe.1
complete -c git-describe -l broken --description 'Describe the state of the working tree.'
complete -c git-describe -l exclude --description 'Do not consider tags matching the given glob(7) pattern, excluding the "refs/…'
complete -c git-describe -l no-match --description 'to clear and reset the list of patterns.'
complete -c git-describe -l no-exclude --description 'to clear and reset the list of patterns.'

