# git-ignore-io
# Autogenerated from man page /usr/local/share/man/man1/git-ignore-io.1
complete -c git-ignore-io -s a -l append --description 'Append new . gitignore content to . gitignore under the current directory.'
complete -c git-ignore-io -s r -l replace --description 'Export new .'
complete -c git-ignore-io -s l -l list-in-table --description 'Print available types in table format.'
complete -c git-ignore-io -s L -l list-alphabetically --description 'Print available types in alphabetical order.'
complete -c git-ignore-io -s s -l search --description 'Search word in available types.'
complete -c git-ignore-io -s t -l show-update-time --description 'Show the last modified time of ~/.'
complete -c git-ignore-io -s u -l update-list --description 'Update ~/. gi_list.'

