# git-grep
# Autogenerated from man page /usr/local/share/man/man1/git-grep.1
complete -c git-grep -l recurse-submodules --description 'Recursively search in each submodule that has been initialized and checked ou…'
complete -c git-grep -l parent-basename --description 'For internal use only.'

