# git-changelog
# Autogenerated from man page /usr/local/share/man/man1/git-changelog.1
complete -c git-changelog -s a -l all --description 'Retrieve all commits.'
complete -c git-changelog -s l -l list --description 'Show commits in list format (without titles, dates).'
complete -c git-changelog -s t -l tag --description 'Specify a tag label to use for most-recent (untagged) commits.'
complete -c git-changelog -s f -l final-tag --description 'When specifying a range, the newest tag at which point commit retrieval will …'
complete -c git-changelog -s s -l start-tag --description 'When specifying a range, the oldest tag to retrieve commits from.'
complete -c git-changelog -s n -l no-merges --description 'Filters out merge commits (commits with more than 1 parent) from generated ch…'
complete -c git-changelog -s m -l merges-only --description 'Uses only merge commits (commits with more than 1 parent) for generated chang…'
complete -c git-changelog -s p -l prune-old --description 'Replace existing changelog entirely with newly generated content, thereby dis…'
complete -c git-changelog -s x -l stdout --description 'Write output to stdout instead of to a new changelog file.'
complete -c git-changelog -s h -l help --description 'Show a help message with basic usage information.'

