# git-ignore
# Autogenerated from man page /usr/local/share/man/man1/git-ignore.1
complete -c git-ignore -s l -l local --description 'Sets the context to the . gitignore file in the current working directory.'
complete -c git-ignore -s g -l global --description 'Sets the context to the global gitignore file for the current user.'
complete -c git-ignore -l ------------------------------- --description 'Local gitignore: . gitignore . cache . project . settings .'

