# groffer
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man1/groffer.1
complete -c groffer -l shell --description '.'
complete -c groffer -l foreground --description '.'
complete -c groffer -l resolution --description '.'
complete -c groffer -l x-viewer -o geometry --description '# # some shell commands if test "$DISPLAY" = ""; then   export DISPLAY=\'local…'

