# gzexe
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man1/gzexe.1
complete -c gzexe -s d --description 'Decompress executables previously compressed by gzexe.'

