# hostname
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man1/hostname.1
complete -c hostname -s f --description 'Include domain information in the printed name.  This is the default behavior.'
complete -c hostname -s s --description 'Trim off any domain information from the printed name.'

