# htdigest
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man1/htdigest.1
complete -c htdigest -s c --description 'Create the passwdfile.  If passwdfile already exists, it is deleted first.'

