# httxt2dbm
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man8/httxt2dbm.8
complete -c httxt2dbm -s o --description 'Name of the output dbm files.  El EXAMPLES httxt2dbm i rewritemap.'

