# iconutil
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man1/iconutil.1
complete -c iconutil -s c --description 'Given the argument iconset, iconutil converts the source \'.'
complete -c iconutil -s o --description 'Overrides the default output file name that iconutil uses to save the convert…'

