# infokey
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man1/infokey.1
complete -c infokey -l output --description 'output to FILE instead of $HOME/. info.'
complete -c infokey -l help --description 'display this help and exit.'
complete -c infokey -l version --description 'display version information and exit.'

