# jconsole
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man1/jconsole.1
complete -c jconsole -o interval --description 'Set the update interval to \\f2n seconds (default is 4 seconds).'
complete -c jconsole -o notile --description 'Do not tile windows initially (for two or more connections).'
complete -c jconsole -o version --description 'Output version information abd exit.'
complete -c jconsole -o help --description 'Output help message and exit.'

