# kadmin
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man8/kadmin.8
complete -c kadmin -s p --description 'principal to authenticate as.'
complete -c kadmin -s K --description 'keytab for authentication principal.'
complete -c kadmin -s c --description 'location of config file.'
complete -c kadmin -s k --description 'location of master key file.'
complete -c kadmin -s r --description 'realm to use.'
complete -c kadmin -s a --description 'server to contact.'
complete -c kadmin -s s --description 'port to use.'
complete -c kadmin -s l --description 'local admin mode El Pp If no command is given on the command line, kadmin wil…'

