# kcc
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man1/kcc.1
complete -c kcc -l version --description 'version information.'
complete -c kcc -l help --description 'help El SEE ALSO kdestroy 1, kinit 1.'

