# ktutil
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man8/ktutil.8
complete -c ktutil -s v --description 'Verbose output.'

