# lam
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man1/lam.1
complete -c lam -s f --description 'Print line fragments according to the format string min .'
complete -c lam -s p --description 'Like f, but pad this file\'s field when end-of-file is reached and other files…'
complete -c lam -s s --description 'Print sepstring before printing line fragments from the next file.'
complete -c lam -s t --description 'The input line terminator is c instead of a newline.'

