# lastcomm
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man1/lastcomm.1
complete -c lastcomm -s f --description 'Read from file rather than the default accounting file.'

