# last
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man1/last.1
complete -c last -s n --description 'Limits the report to n lines.'
complete -c last -s h --description 'Host names may be names or internet numbers.'
complete -c last -s t --description 'Specify the tty.'

