# localemanager
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man8/localemanager.8
complete -c localemanager -s l --description 'Locale name.'
complete -c localemanager -o subnet --description 'Subnet specified in CIDR notation.'
complete -c localemanager -o server --description 'Server fully-qualified domain name.'
complete -c localemanager -s i --description 'Use this IP address for the server.'

