# logdump
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/usr/share/man/man1/logdump.1
complete -c logdump -l archive --description 'Pass the path to a . logarchive directory.'
complete -c logdump -l file --description 'Pass the path to a specific logdata. tracev3 file.'
complete -c logdump -l filter --description 'Stream will filter messages based on the provided (required) query argument.'
complete -c logdump -l no-sensitive --description 'Do not dump sensitive private information.'
complete -c logdump -l source --description 'Include symbol names and source line numbers for messages.'
complete -c logdump -l style --description 'Output the content as a different style (i. e. , json, syslog).'

