# look
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man1/look.1
complete -c look -s d --description 'Dictionary character set and order, i. e.'
complete -c look -s f --description 'Ignore the case of alphabetic characters.'
complete -c look -s t --description 'Specify a string termination character, i. e.'

