# lprm
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man1/lprm.1.gz
complete -c lprm -s E --description 'Forces encryption when connecting to the server.'
complete -c lprm -s P --description 'Specifies the destination printer or class.'
complete -c lprm -s U --description 'Specifies an alternate username.'
complete -c lprm -s h --description 'Specifies an alternate server.'

