# lsappinfo
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man8/lsappinfo.8
complete -c lsappinfo -s v -l verbose --description '.'
complete -c lsappinfo -s q -l quiet --description '.'
complete -c lsappinfo -o defaultSession --description '.'
complete -c lsappinfo -o currentSession --description '.'
complete -c lsappinfo -o debug -o info -o notice -o warning -o err -o critical -o alert -o emergency --description '.'

