# mcxquery
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man1/mcxquery.1
complete -c mcxquery -o user --description 'Specify the short name of the user record to read managed preferences from.'
complete -c mcxquery -o group --description 'Specify the short name of the group record to read managed preferences from.'
complete -c mcxquery -o computer --description 'Specify the computer record to read managed preferences from.'

