# mcxrefresh
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man1/mcxrefresh.1
complete -c mcxrefresh -s u --description 'Specify the numeric user id of the user to be refreshed.'
complete -c mcxrefresh -s n --description 'Specify the short name of the user to be refreshed.'
complete -c mcxrefresh -s a --description 'Ask for authentication and pass it to ManagedClient.  El Pp.'

