# mDNSResponder
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man8/mDNSResponder.8
complete -c mDNSResponder -o AlwaysAppendSearchDomains --description 'Append search domains for multi-labeled Partially Qualified Domain Name as we…'
complete -c mDNSResponder -o NoMulticastAdvertisements --description 'Prevent the system from advertising Bonjour services via Multicast DNS.'

