# mkdir
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man1/mkdir.1
complete -c mkdir -s m --description 'Set the file permission bits of the final created directory to the specified …'
complete -c mkdir -s p --description 'Create intermediate directories as required.'
complete -c mkdir -s v --description 'Be verbose when creating directories, listing them as they are created.'

