# mkfifo
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man1/mkfifo.1
complete -c mkfifo -s m --description 'Set the file permission bits of newly-created fifos to mode, without respect …'

