# mkfile
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man8/mkfile.8
complete -c mkfile -s n --description 'Create an empty R filename .'
complete -c mkfile -s v --description 'Verbose.   Report the names and sizes of created files.'

