# mklocale
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man1/mklocale.1
complete -c mklocale -s d --description 'Turns on debugging messages.'
complete -c mklocale -s o --description 'Specify output file.'

