# mmroff
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man1/mmroff.1
complete -c mmroff -s x --description 'Just create the reference file.'

