# mount_cd9660
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man8/mount_cd9660.8
complete -c mount_cd9660 -s e --description 'Enable the use of extended attributes.'
complete -c mount_cd9660 -s g --description 'Do not strip version numbers on files.'
complete -c mount_cd9660 -s j --description 'Do not use any Joliet extensions included in the filesystem.'
complete -c mount_cd9660 -s o --description 'Options are specified with a o flag followed by a comma separated string of o…'
complete -c mount_cd9660 -s r --description 'Do not use any Rockridge extensions included in the filesystem.'
complete -c mount_cd9660 -s s --description 'Start the filesystem at startsector.'

