# mount_url
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man8/mount_url.8
complete -c mount_url -s n --description 'The mount should be done through the NetAuth agent.'
complete -c mount_url -s o --description 'Options are specified with a o flag followed by a comma separated string of o…'
complete -c mount_url -s r --description 'The file system is to be mounted read-only.'
complete -c mount_url -s w --description 'The file system object is to be read and write.'

