# mount_exfat
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man8/mount_exfat.8
complete -c mount_exfat -s o --description 'Use the specified mount options, as described in mount 8.'
complete -c mount_exfat -s u --description 'Set the owner of the files in the file system to uid.'
complete -c mount_exfat -s g --description 'Set the group of the files in the file system to gid.'
complete -c mount_exfat -s m --description 'Specify the maximum file permissions for files in the file system.'

