# msdos
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man8/msdos.util.8
complete -c msdos -s m --description 'mount.'
complete -c msdos -s n --description 'set name.'
complete -c msdos -s p --description 'probe for mounting.'
complete -c msdos -s u --description 'unmount.'
complete -c msdos -s k --description 'print volume UUID El Pp mountflags above are either: -bullet -compact -offset…'

