# nbdst
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man8/nbdst.8
complete -c nbdst -o recycle --description 'If a shadow file already exists, reset it and use it again.'
complete -c nbdst -o preallocate --description 'Set the shadow file to the given size up front.'

