# nfs4mapid
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man8/nfs4mapid.8
complete -c nfs4mapid -s G --description 'Map an NFSv4 string to a gid.'
complete -c nfs4mapid -s u --description 'Map a uid to an NFSv4 user@domain string.'
complete -c nfs4mapid -s g --description 'Map a gid to an NFSv4 group@domain string.'

