# nfsiod
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man8/nfsiod.8
complete -c nfsiod -s n --description 'Specify maximum number of asynchronous I/O threads to be used.'

