# nlcontrol
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man8/nlcontrol.8
complete -c nlcontrol -o domain --description 'The service will log extensive debug information and may perform extra diagno…'
complete -c nlcontrol -o help --description 'Prints a usage message and exits.'
complete -c nlcontrol -o server --description 'The service will listen on each of the TCP ports specified in the comma-separ…'

