# npm-dist-tag
# Autogenerated from man page /Users/icylace/.nvm/versions/node/v8.1.2/share/man/man1/npm-dist-tag.1
complete -c npm-dist-tag -l tag --description 'o 2 rm: Clear a tag that is no longer in use from the package.'

