# ntpd
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man1/ntpd.1
complete -c ntpd -o '\\&?' --description 'Display usage information and exit.'
complete -c ntpd -o '\\&!' --description 'Pass the extended usage information through a pager.'
complete -c ntpd -o '\\-version' --description 'Output version of program and exit.'

