# ntptrace
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man1/ntptrace.1
complete -c ntptrace -o '\\&?' --description 'Display usage information and exit.'
complete -c ntptrace -o '\\&!' --description 'Pass the extended usage information through a pager.'
complete -c ntptrace -s v --description 'Output version of program and exit.'

