# nvram
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man8/nvram.8
complete -c nvram -s d --description 'Deletes the named firmware variable. \\" ==========.'
complete -c nvram -s f --description 'Set firmware variables from a text file.'
complete -c nvram -s x --description 'Use XML format for reading and writing variables.'
complete -c nvram -s c --description 'Delete all of the firmware variables.'
complete -c nvram -s p --description 'or.'

