# odmigrationtool
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man1/odmigrationtool.1
complete -c odmigrationtool -o source --description 'source volume or path to migrate from.'
complete -c odmigrationtool -o target --description 'destination volume or path to mirage to.'

