# osascript
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man1/osascript.1
complete -c osascript -s e --description 'Enter one line of a script.'
complete -c osascript -s i --description 'Interactive mode: osascript will prompt for one line at a time, and print the…'
complete -c osascript -s l --description 'Override the language for any plain text files.'
complete -c osascript -s s --description 'Modify the output style.'

