# parsec_tool
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man1/parsec_tool.1
complete -c parsec_tool -s a --description 'Description of -a flag.'
complete -c parsec_tool -s b --description 'Description of -b flag \\" Ends the list Pp .'

