# path_helper
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man8/path_helper.8
complete -c path_helper -s c --description 'Generate C-shell commands on stdout.'
complete -c path_helper -s s --description 'Generate Bourne shell commands on stdout.'

