# pathchk
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man1/pathchk.1
complete -c pathchk -s p --description 'Perform portability checks on the specified pathname arguments.'

