# pbcopy
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man1/pbcopy.1
complete -c pbcopy -o pboard --description 'specifies which pasteboard to copy to or paste from.'
complete -c pbcopy -o Prefer --description 'tells pbpaste what type of data to look for in the pasteboard first.'

