# pkreporter
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man8/pkreporter.8
complete -c pkreporter -s v --description 'Enable verbose output.  \\" Ends the list Pp .'

