# pl
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man1/pl.1
complete -c pl -l input --description 'Cause pl to use the specified file as input.'
complete -c pl -l output --description 'Cause pl to use the specified file as output.'

