# pod2text5
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man1/pod2text5.18.1
complete -c pod2text5 -o errors --description 'Set the error handling style.'
complete -c pod2text5 -l nourls --description 'Normally, L<> formatting codes with a \\s-1URL\\s0 but anchor text are formatte…'

