# postkick
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man1/postkick.1
complete -c postkick -s c --description 'Read the main.'
complete -c postkick -s v --description 'Enable verbose logging for debugging purposes.'

