# postdrop
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man1/postdrop.1
complete -c postdrop -s c --description 'The main.'
complete -c postdrop -s r --description 'Use a Postfix-internal protocol for reading the message from standard input, …'
complete -c postdrop -s v --description 'Enable verbose logging for debugging purposes.'

