# ppdi
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man1/ppdi.1.gz
complete -c ppdi -s I --description 'Specifies an alternate include directory.'
complete -c ppdi -s o --description 'Specifies the PPD source file to update.'

