# ppdmerge
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man1/ppdmerge.1.gz
complete -c ppdmerge -s o --description 'Specifies the PPD file to create.'

