# ppdpo
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man1/ppdpo.1.gz
complete -c ppdpo -s D --description 'Sets the named variable for use in the source file.'
complete -c ppdpo -s I --description 'Specifies an alternate include directory.'
complete -c ppdpo -s o --description 'Specifies the output file.  The supported extensions are . po or . po.'

