# ptargrep5
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man1/ptargrep5.16.1
complete -c ptargrep5 -l basename -s b --description 'When matching files are extracted, ignore the directory path from the archive…'
complete -c ptargrep5 -l ignore-case -s i --description 'Make pattern matching case-insensitive.'
complete -c ptargrep5 -l list-only -s l --description 'Print the pathname of each matching file from the archive to \\s-1STDOUT\\s0.'
complete -c ptargrep5 -l verbose -s v --description 'Log debugging info to \\s-1STDERR\\s0.'

