# ptf_validator
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man1/ptf_validator.1
complete -c ptf_validator -s a --description 'Description of -a flag.'
complete -c ptf_validator -s b --description 'Description of -b flag \\" Ends the list Pp .'

