# pwd
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man1/pwd.1
complete -c pwd -s L --description 'Display the logical current working directory.'
complete -c pwd -s P --description 'Display the physical current working directory (all symbolic links resolved).'

