# python2
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man1/python2.7.1
complete -c python2 -o OO --description 'Discard docstrings in addition to the -O optimizations.'

