# rarpd
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man8/rarpd.8
complete -c rarpd -s a --description 'Listen on all the Ethernets attached to the system.'
complete -c rarpd -s d --description 'Run in debug mode, with all the output to stderr.'
complete -c rarpd -s f --description 'Run in the foreground.'

