# reboot
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man8/reboot.8
complete -c reboot -s l --description 'The halt or reboot is not recorded in the system log.'
complete -c reboot -s n --description 'The file system cache is not flushed.'
complete -c reboot -s q --description 'The system is halted or restarted quickly and ungracefully, and only the flus…'
complete -c reboot -s u --description 'The system is halted up until the point of removing system power, but waits b…'

