# reject
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man8/reject.8.gz
complete -c reject -s E --description 'Forces encryption when connecting to the server.'
complete -c reject -s U --description 'Sets the username that is sent when connecting to the server.'
complete -c reject -s h --description 'Chooses an alternate server.'
complete -c reject -s r --description 'Sets the reason string that is shown for a printer that is rejecting jobs.'

