# rmdir
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man1/rmdir.1
complete -c rmdir -s p --description 'Each directory argument is treated as a pathname of which all components will…'

