# rmiregistry
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man1/rmiregistry.1
complete -c rmiregistry -s J --description 'Used in conjunction with any java option, this option passes option (no space…'

