# rpcinfo
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man8/rpcinfo.8
complete -c rpcinfo -s T --description 'Specify the netid to use.  Supported netids are udp, tcp, udp6, and tcp6.'
complete -c rpcinfo -s h --description 'Print out the synopsis of this program.'

