# safaridriver
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man1/safaridriver.1
complete -c safaridriver -s p --description 'Specifies the port on which the HTTP server should listen for incoming connec…'

