# sandboxd
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man8/sandboxd.8
complete -c sandboxd -s b --description 'Just log basic sandbox violation information without a backtrace.'
complete -c sandboxd -s s --description 'Do not symbolicate backtraces.'

