# snmpusm
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man1/snmpusm.1
complete -c snmpusm -o CE --description 'Set usmUserEngineID to be used as part of the index of the usmUserTable.'
complete -c snmpusm -o Cp --description 'Set the usmUserPublic value of the (new) user to the specified STRING.'
complete -c snmpusm -o Ca --description 'Change the authentication key.'
complete -c snmpusm -o Cx --description 'Change the privacy key.'
complete -c snmpusm -o Ck --description 'Allows to use localized key (must start with 0x) instead of passphrase.'

