# snmpbulkget
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man1/snmpbulkget.1
complete -c snmpbulkget -o Cn --description 'Set the  non-repeaters field in the GETBULK PDU.'
complete -c snmpbulkget -o Cr --description 'Set the max-repetitions field in the GETBULK PDU.'

