# snmpdf
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man1/snmpdf.1
complete -c snmpdf -o Cu --description 'Forces the command to use dskTable in mib UCD-SNMP-MIB instead of the default…'

