# snmpstatus
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man1/snmpstatus.1
complete -c snmpstatus -o Cf --description 'option is given, see below), but this variable will then be missing from the …'

