# soelim
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man1/soelim.1
complete -c soelim -s C --description 'Recognize  . so even when followed by a character other than space or newline.'
complete -c soelim -s I --description 'This option may be used to specify a directory to search for files (both thos…'
complete -c soelim -s r --description 'Do not add . lf requests (for general use, with non-groff files).'
complete -c soelim -s t --description 'Don\'t emit .'
complete -c soelim -s s --description 'option of groff .'
complete -c soelim -s v --description 'Print the version number.'

