# ssh-copy-id
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man1/ssh-copy-id.1
complete -c ssh-copy-id -s i --description 'Use only the key(s) contained in identity_file (rather than looking for ident…'
complete -c ssh-copy-id -s f --description 'Forced mode: doesn\'t check if the keys are present on the remote server.'
complete -c ssh-copy-id -s n --description 'do a dry-run.'
complete -c ssh-copy-id -s h --description 'Print Usage summary.'
complete -c ssh-copy-id -s p --description 'These two options are simply passed through untouched, along with their argum…'

