# swiftenv-install
# Autogenerated from man page /Users/icylace/.swiftenv/share/man/man1/swiftenv-install.1
complete -c swiftenv-install -l verbose --description 'Shows additional debugging information.'
complete -c swiftenv-install -l list --description 'Lists all the Swift releases that can be installed.'
complete -c swiftenv-install -l list-snapshots --description 'Lists all the Swift snapshot releases that can be installed.'
complete -c swiftenv-install -l build --description 'Forces installation only from source.'
complete -c swiftenv-install -l no-build --description 'Forces installation only from binary releases of Swift.'
complete -c swiftenv-install -l no-clean --description 'Leaves the build directory intact for inspection and debugging.'

