# swiftenv
# Autogenerated from man page /Users/icylace/.swiftenv/share/man/man1/swiftenv.1
complete -c swiftenv -l version --description 'Prints the version of Swiftenv.'
complete -c swiftenv -l help --description 'Prints the synopsis and a list of the most commonly used commands.  COMMANDS.'

