# tailspin
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man1/tailspin.1
complete -c tailspin -s r --description 'Include a key in the tailspin file indicating why it was saved.'
complete -c tailspin -s l --description 'Limit the data in tailspin file to that of the last num-seconds.'
complete -c tailspin -s n --description 'Save tailspin file without symbolicating.'
complete -c tailspin -s v --description 'Print layout information of tailspin file.'

