# tee
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man1/tee.1
complete -c tee -s a --description 'Append the output to the files rather than overwriting them.'
complete -c tee -s i --description 'Ignore the SIGINT signal.'

