# tfmtodit
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man1/tfmtodit.1
complete -c tfmtodit -s v --description 'Print the version number.'
complete -c tfmtodit -s s --description 'The font is special.'
complete -c tfmtodit -s k --description 'The skewchar of this font is at position R n .'
complete -c tfmtodit -s g --description 'option.  The.'

