# time
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man1/time.1
complete -c time -s l --description 'The contents of the rusage structure are printed.'
complete -c time -s p --description 'The output is formatted as specified by -p1003. 2-92.'

