# traptoemail
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man1/traptoemail.1
complete -c traptoemail -s f --description 'sender address, defaults to "root".'
complete -c traptoemail -s s --description 'SMTP server, defaults to "localhost".'

