# unexpand
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man1/unexpand.1
complete -c unexpand -s a --description 'unexpand ( unexpand only.'
complete -c unexpand -s t --description 'Set tab stops at column positions tab1 , tab2 , .  , tabn.'

