# unzipsfx
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man1/unzipsfx.1
complete -c unzipsfx -s j -s V --description 'following operating-system specific options:  -X (restore VMS owner/protectio…'

