# w
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man1/w.1
complete -c w -s h --description 'Suppress the heading.'
complete -c w -s i --description 'Output is sorted by idle time.'

