# wall
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man1/wall.1
complete -c wall -s g --description 'Send messages to users in this group.'

