# wc
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man1/wc.1
complete -c wc -s c --description 'The number of bytes in each input file is written to the standard output.'
complete -c wc -s l --description 'The number of lines in each input file is written to the standard output.'
complete -c wc -s m --description 'The number of characters in each input file is written to the standard output.'
complete -c wc -s w --description 'The number of words in each input file is written to the standard output.'

