# which
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man1/which.1
complete -c which -s a --description 'List all instances of executables found (instead of just the first one of eac…'
complete -c which -s s --description 'No output, just return 0 if any of the executables are found, or 1 if none ar…'

