# WirelessRadioManagerd
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man1/WirelessRadioManagerd.1
complete -c WirelessRadioManagerd -s a --description 'Description of -a flag.'
complete -c WirelessRadioManagerd -s b --description 'Description of -b flag \\" Ends the list Pp .'

