# yadm
# Autogenerated from man page /usr/local/share/man/man1/yadm.1
complete -c yadm -s Y -l yadm-dir --description 'Override the  yadm directory.'
complete -c yadm -l yadm-repo --description 'Override the location of the  yadm repository.'
complete -c yadm -l yadm-config --description 'Override the location of the  yadm configuration file.'
complete -c yadm -l yadm-encrypt --description 'Override the location of the  yadm encryption configuration.'
complete -c yadm -l yadm-archive --description 'Override the location of the  yadm encrypted files archive.'
complete -c yadm -s w --description 'yadm can be forced to overwrite an existing repository by providing the.'
complete -c yadm -s f --description 'By default yadm will ask the user if the bootstrap program should be run (if …'
complete -c yadm -l bootstrap -l no-bootstrap --description 'will either force the bootstrap to be run, or prevent it from being run, with…'
complete -c yadm -s l --description 'option will list the files stored without extracting them.'
complete -c yadm -l yadm-bootstrap --description 'Override the location of the yadm bootstrap program.'

