# ypcat
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man1/ypcat.1
complete -c ypcat -s d --description 'Specify a domain other than the default domain.'
complete -c ypcat -s k --description 'Display map keys.'
complete -c ypcat -s t --description 'Inhibit translation of map nicknames to their corresponding map names.'
complete -c ypcat -s x --description 'Display the map nickname table.'

