# yppoll
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man/man8/yppoll.8
complete -c yppoll -s d --description 'Don\'t use default domain, use the specified domain.'
complete -c yppoll -s h --description 'Get map information from host instead of the default YP server.'

