# zplug
# Autogenerated from man page /usr/local/Cellar/zplug/HEAD-5e7921a/share/man/man1/zplug.1
complete -c zplug -l help --description 'Print the synopsis and a list of all available commands.'
complete -c zplug -l version --description 'Print zplug\\(cqs version.'
complete -c zplug -l log --description 'Show the error log.'
complete -c zplug -l verbose --description 'option is given, print extra debugging information.'
complete -c zplug -l force --description 'option is given, suppress the prompt and uninstall package.  If the.'
complete -c zplug -l select --description 'option is given, by using the filter specified in $ZPLUG_FILTER, interactivel…'

